### PR TITLE
Extend mapping module with AOs

### PR DESCRIPTION
**Pull request by dcworldwide**

### CODE REVIEW

**Comment by dcworldwide** [comment]
@DavidWhittingham Ready to review, merge and release please :)

**Comment by dcworldwide** [comment]
I have 1 change to make before we can merge.... will update you.

**Comment by dcworldwide** [comment]
@DavidWhittingham  ok ready to go. Added a fix to handle broken datasources.

**Comment by DavidWhittingham** [comment]
Merged manually with rebase

**Pull request closed without merging**
