### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by adamkerz**
My code for handling GPServices and Python toolboxes

### CODE REVIEW

**Comment by DavidWhittingham** [comment]
Pretty happy to merge this, but just note, the PythonToolbox class will have it's methods renamed to underscore_case to match with the rest of the library.  I'll probably want to add some tests at some point as well.

**Comment by adamkerz** [comment]
Fair enough, do you want me to do the underscores or are you already into it. And yep, tests... Once I've got the ClipZipShip up and running this week I can get onto that.

**Comment by adamkerz** [comment]
I actually put together a package of both this and agsadmin (bumped version number and added +adam) and put into our sirpypi repo so that Dave Ahrens can do dev work, but looks like he's not going to for a bit, so I can drop them if we get new releases of these two. Which reminds me, looks like I've got a pull request for agsadmin ready to go too...

**Comment by DavidWhittingham** [comment]
If you've got the time, feel free to add the underscores.
________________________________

**Pull request merged**
